# Generated by Django 5.2.17 on 2026-09-10 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('experience_min', models.PositiveIntegerField(default=0, help_text='Minimum years of experience')),
                ('experience_max', models.PositiveIntegerField(default=0, help_text='Maximum years of experience')),
                ('education_required', models.CharField(blank=True, max_length=200)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for ATS keyword matching')),
                ('num_openings', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_roles', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative importance of this skill')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='jobs.jobrole')),
            ],
            options={
                'unique_together': {('job_role', 'skill_name')},
            },
        ),
    ]
