# Generated by Django 5.2.17 on 2026-09-10 09:45

import django.db.models.deletion
import resumes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.validators.resume_upload_path, validators=[resumes.validators.validate_resume_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('parsed_text', models.TextField(blank=True)),
                ('parsed_name', models.CharField(blank=True, max_length=150)),
                ('parsed_email', models.EmailField(blank=True, max_length=254)),
                ('parsed_phone', models.CharField(blank=True, max_length=20)),
                ('parsing_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parsing_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
