# Generated by Django 5.2.17 on 2026-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='recommended_department_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='recommended_department_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
