# Generated by Django 5.2.17 on 2026-09-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidateprofile')),
                ('source_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_skills', to='resumes.resume')),
            ],
            options={
                'ordering': ['skill_name'],
                'unique_together': {('candidate', 'skill_name')},
            },
        ),
    ]
