# Generated by Django 5.2.17 on 2026-09-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_match_pct', models.FloatField()),
                ('experience_match_pct', models.FloatField()),
                ('education_match_pct', models.FloatField()),
                ('projects_pct', models.FloatField()),
                ('certifications_pct', models.FloatField()),
                ('keywords_pct', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('explanation', models.JSONField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_results', to='jobs.jobrole')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_results', to='resumes.resume')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
